async function Vips(moduleArg={}){var moduleRtn;var n=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,r=ba&&globalThis.name=="em-pthread";n.dynamicLibraries=n.dynamicLibraries||["vips-jxl.wasm","vips-heif.wasm"];var ca=[],da="./this.program",ea=import.meta.url,fa="";function ha(a){return n.locateFile?n.locateFile(a,fa):fa+a}var ia,ja;
if(aa||ba){try{fa=(new URL(".",ea)).href}catch{}ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ia=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var la=console.log.bind(console),w=console.error.bind(console),ma=[],na,oa,pa=!1,qa,ra,sa,ta={},va;
if(r){var wa=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.V;if(d==1){let e=[];self.onmessage=f=>e.push(f);va=()=>{postMessage({V:3});for(let f of e)a(f);self.onmessage=a};ma=c.Hb;ta=c.sc;for(let f of c.Tb)if(!n[f]||n[f].proxy)n[f]=(...g)=>{postMessage({V:9,Sb:f,Bb:g})},f=="print"&&(la=n[f]),f=="printErr"&&(w=n[f]);xa=c.zc;ya();oa=c.Ac;za();Aa()}else if(d==2){Ba(c.X);Ca(c.X,0,0,1,0,0);Da();Ea(c.X);wa||(Fa(),wa=!0);try{Ga(c.vc,c.Ea)}catch(e){if(e!="unwind")throw e;
}}else d==4?wa&&Ha():d&&(w(`worker: received unknown command ${d}`),w(c))}catch(e){throw Ia(),e;}}self.onmessage=a}var Ja=!1,Ka=!1;function ya(){var a=xa.buffer;x=new Int8Array(a);y=new Int16Array(a);A=new Uint8Array(a);E=new Uint16Array(a);F=new Int32Array(a);G=new Uint32Array(a);La=new Float32Array(a);Ma=new Float64Array(a);H=new BigInt64Array(a);Na=new BigUint64Array(a)}var Oa=[];function Pa(){Ja=!0;r?va():(Qa(Oa),n.noFSInit||FS.Ia||FS.init(),Ra.__wasm_call_ctors(),Qa(Sa),FS.fb=!1)}
function I(a){n.onAbort?.(a);a=`Aborted(${a})`;w(a);pa=!0;a+=". Build with -sASSERTIONS for more info.";Ja&&Ta();a=new WebAssembly.RuntimeError(a);sa?.(a);throw a;}var Ua;async function Va(a){if(!na)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==Ua&&na)a=new Uint8Array(na);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Wa(a,b){try{var c=await Va(a);return await WebAssembly.instantiate(c,b)}catch(d){w(`failed to asynchronously prepare wasm: ${d}`),I(d)}}async function Ya(a){var b=Ua;if(!na)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){w(`wasm streaming compile failed: ${d}`),w("falling back to ArrayBuffer instantiation")}return Wa(b,a)}
function Za(){J={__assert_fail:$a,__call_sighandler:ab,__lsan_ignore_object:bb,__pthread_create_js:cb,__syscall_dup:db,__syscall_faccessat:eb,__syscall_fcntl64:fb,__syscall_fstat64:gb,__syscall_ftruncate64:hb,__syscall_getcwd:ib,__syscall_ioctl:jb,__syscall_lstat64:kb,__syscall_newfstatat:lb,__syscall_openat:mb,__syscall_poll:nb,__syscall_rmdir:ob,__syscall_stat64:pb,__syscall_unlinkat:qb,__throw_exception_with_stack_trace:rb,_abort_js:sb,_dlopen_js:tb,_dlsym_catchup_js:ub,_dlsym_js:xb,_embind_finalize_value_object:yb,
_embind_register_arithmetic_vector:zb,_embind_register_bigint:Ab,_embind_register_bool:Bb,_embind_register_class:Cb,_embind_register_class_class_function:Db,_embind_register_class_constructor:Eb,_embind_register_class_function:Fb,_embind_register_class_property:Gb,_embind_register_emval:Hb,_embind_register_enum:Ib,_embind_register_enum_value:Jb,_embind_register_float:Kb,_embind_register_function:Lb,_embind_register_integer:Mb,_embind_register_iterable:Nb,_embind_register_memory_view:Ob,_embind_register_optional:Pb,
_embind_register_std_string:Qb,_embind_register_std_wstring:Rb,_embind_register_value_object:Sb,_embind_register_value_object_field:Tb,_embind_register_void:Ub,_emscripten_dlopen_js:Vb,_emscripten_dlsync_threads:Wb,_emscripten_get_dynamic_libraries_js:Xb,_emscripten_init_main_thread_js:Yb,_emscripten_notify_mailbox_postmessage:Zb,_emscripten_receive_on_main_thread_js:$b,_emscripten_runtime_keepalive_clear:ac,_emscripten_thread_cleanup:bc,_emscripten_thread_exit_joinable:cc,_emscripten_thread_mailbox_await:Ea,
_emscripten_thread_set_strongref:dc,_emval_array_to_memory_view:ec,_emval_create_invoker:fc,_emval_decref:hc,_emval_get_global:ic,_emval_get_module_property:jc,_emval_get_property:kc,_emval_incref:lc,_emval_instanceof:mc,_emval_invoke:nc,_emval_is_number:oc,_emval_is_string:pc,_emval_new_cstring:qc,_emval_run_destructors:rc,_emval_set_property:sc,_emval_typeof:tc,_gmtime_js:uc,_localtime_js:vc,_mmap_js:wc,_munmap_js:xc,_tzset_js:yc,clock_time_get:zc,emscripten_check_blocking_allowed:Ac,emscripten_date_now:Bc,
emscripten_err:Cc,emscripten_exit_with_live_runtime:Dc,emscripten_get_heap_max:Ec,emscripten_get_now:Fc,emscripten_num_logical_cores:Gc,emscripten_promise_destroy:Hc,emscripten_promise_resolve:Ic,emscripten_resize_heap:Jc,environ_get:Kc,environ_sizes_get:Lc,exit:Mc,fd_close:Nc,fd_fdstat_get:Oc,fd_read:Pc,fd_seek:Qc,fd_write:Rc,ffi_call_js:Sc,heif_error_success:Tc,memory:xa,proc_exit:Uc,random_get:Vc};var a=new Proxy(new Set(["__lsan_ignore_object"]),Wc);return{env:J,wasi_snapshot_preview1:J,"GOT.mem":a,
"GOT.func":a}}
async function za(){function a(d,e){var f=Ra=d.exports;Xc(Ra);var g=Yc(e);Zc(Ra._emscripten_tls_init,d.exports,g);d=Ra;$c=d.pthread_self;ad=d.malloc;n._main=d.main;L=d.free;bd=d.fflush;cd=d.calloc;n.__ZnamSt11align_val_t=d._ZnamSt11align_val_t;dd=d.__getTypeName;Fa=d._embind_initialize_bindings;n._emscripten_builtin_free=d.emscripten_builtin_free;ed=d.emscripten_builtin_memalign;n._emscripten_builtin_malloc=d.emscripten_builtin_malloc;fd=d.__funcs_on_exit;n.___libc_calloc=d.__libc_calloc;n.___libc_free=
d.__libc_free;n.___libc_malloc=d.__libc_malloc;gd=d.__dl_seterr;hd=d._emscripten_dlsync_self_async;jd=d._emscripten_dlsync_self;kd=d._emscripten_proxy_dlsync_async;ld=d._emscripten_proxy_dlsync;md=d._emscripten_find_dylib;Ca=d._emscripten_thread_init;nd=d.__set_thread_state;Ia=d._emscripten_thread_crashed;od=d._emscripten_run_js_on_main_thread_done;pd=d._emscripten_run_js_on_main_thread;qd=d._emscripten_thread_free_data;rd=d._emscripten_thread_exit;n._strndup=d.strndup;sd=d._emscripten_check_mailbox;
n.__ZdaPvm=d._ZdaPvm;n.___libc_realloc=d.__libc_realloc;n._emscripten_builtin_calloc=d.emscripten_builtin_calloc;n._emscripten_builtin_realloc=d.emscripten_builtin_realloc;n._malloc_size=d.malloc_size;n._malloc_usable_size=d.malloc_usable_size;n._reallocf=d.reallocf;td=d.emscripten_get_sbrk_ptr;Ta=d.__trap;ud=d.emscripten_stack_set_limits;vd=d._emscripten_stack_restore;wd=d._emscripten_stack_alloc;xd=d.emscripten_stack_get_current;yd=d.__thrown_object_from_unwind_exception;zd=d.__get_exception_message;
M=d.__indirect_function_table;Ad=d.__cpp_exception;Bd=d.__heap_base.value;Cd(f);Dd("__main__",0,J);Ed();oa=e;return Ra}var b=Za();if(n.instantiateWasm)return new Promise(d=>{n.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(r){var c=new WebAssembly.Instance(oa,Za());return a(c,oa)}Ua??=n.locateFile?ha("vips.wasm"):(new URL("vips.wasm",import.meta.url)).href;return function(d){return a(d.instance,d.module)}(await Ya(b))}var Gd=a=>{if(!(a instanceof Fd||a=="unwind"))throw a;};
class Fd{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var N=0,Hd=a=>{a.terminate();a.onmessage=()=>{}},Md=a=>{var b=Id[a];Jd.delete(a);a in Kd&&Kd[a].resolve();a=b.X;delete Id[a];Ld.push(b);b.X=0;qd(a)},Qa=a=>{for(;a.length>0;)a.shift()(n)},Nd=[],Od=()=>{var a=n.preRun.shift();Nd.push(a)},Pd=a=>{Jd.add(a);a in Kd&&Kd[a].resolve()},Qd=0,Rd=null,Sd=()=>{Qd--;n.monitorRunDependencies?.(Qd);if(Qd==0&&Rd){var a=Rd;Rd=null;a()}},Td=()=>{Qd++;n.monitorRunDependencies?.(Qd)},Wd=a=>{if(Ld.length==0){var b=Ud();Vd(b)}b=Ld.pop();if(!b)return 6;Id[a.X]=b;b.X=a.X;
b.postMessage({V:2,vc:a.uc,Ea:a.Ea,X:a.X},a.wc);return 0},Xd=!Atomics.waitAsync||globalThis.navigator?.userAgent&&Number((navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)||[])[2])<91,Ld=[],Yd=[],Id={},Kd={},Jd=new Set;function Zd(){for(var a=navigator.hardwareConcurrency>6?navigator.hardwareConcurrency:6;a--;)Ud();Nd.push(async()=>{var b=$d();Td("loading-workers");await b;Sd("loading-workers")})}var ae=()=>{for(var a of Object.values(Id))Hd(a);for(a of Ld)Hd(a);Ld=[];Id={}};
function Da(){Yd.forEach(a=>a())}
var Vd=a=>new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.V;if(g.rb)Id[g.rb]?.postMessage(g);else if(g==="setimmediate"||g==="_si")a.postMessage(g);else switch(f){case 4:Ha();break;case 5:Wd(g);break;case 6:be(()=>Md(g.Ua));break;case 7:Pd(g.Ua);break;case 3:b(a);break;case 9:n[g.Sb](...g.Bb);break;default:f&&w(`worker sent an unknown command ${f}`)}};a.onerror=f=>{w(`worker sent an error! ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)n.propertyIsEnumerable(e)&&
c.push(e);a.postMessage({V:1,Tb:c,zc:xa,Ac:oa,Hb:ma,sc:ta})});async function $d(){if(!r)return Promise.all(Ld.map(Vd))}function Ud(){if(n.mainScriptUrlOrBlob){var a=n.mainScriptUrlOrBlob;typeof a!="string"&&(a=URL.createObjectURL(a));a=new Worker(a,{type:"module",name:"em-pthread"})}else a=new Worker(new URL("vips-es6.js",import.meta.url),{type:"module",name:"em-pthread"});Ld.push(a);return a}
var ce,O=(a,b,...c)=>{var d=8*c.length*2,e=xd(),f=wd(d),g=f>>3,h;for(h of c)typeof h=="bigint"?(H[g++]=1n,H[g++]=h):(H[g++]=0n,Ma[g++]=h);a=pd(a,0,d,f,b);vd(e);return a};function Uc(a){if(r)return O(0,1,a);qa=a;de||N>0||(ae(),n.onExit?.(a),pa=!0);throw new Fd(a);}Uc.g="vi";function ee(a){if(r)return O(1,0,a);Mc(a)}var Mc=a=>{qa=a;if(r)throw ee(a),"unwind";if(!(de||N>0)){fd();FS.Ia=!1;bd(0);for(var b of FS.streams)b&&FS.close(b);ae();b=$c();nd(0,0,0,1);Xd||Atomics.notify(F,b>>2);Ka=!0}Uc(a)};
Mc.g="vi";var be=a=>{if(!Ka&&!pa)try{a()}catch(b){Gd(b)}finally{if(!(Ka||de||N>0))try{r?$c()&&rd(qa):Mc(qa)}catch(b){Gd(b)}}},fe=a=>{N+=1;setTimeout(()=>{--N;be(a)},1E4)},ge=[],he={},ie=!1;
function je(){function a(){ie=document.pointerLockElement===n.canvas}if(!ke){ke=!0;ge.push({canHandle:c=>!n.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:le(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:le(d)}));var f=URL.createObjectURL(e);return new Promise((g,h)=>{var k=new Image;k.onload=()=>{var l=document.createElement("canvas");l.width=k.width;l.height=k.height;l.getContext("2d").drawImage(k,0,0);URL.revokeObjectURL(f);
g(c)};k.onerror=()=>{w(`Image ${f} could not be decoded`);h()};k.src=f})}});ge.push({canHandle:c=>!n.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,h=URL.createObjectURL(new Blob([c],{type:le(d)})),k=new Audio;k.addEventListener("canplaythrough",()=>f(k),!1);k.onerror=()=>{if(!g){w(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var l="",m=0,q=0,t=0;t<c.length;t++)for(m=m<<
8|c[t],q+=8;q>=6;){var p=m>>q-6&63;q-=6;l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[p]}q==2?(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&3)<<4],l+="=="):q==4&&(l+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(m&15)<<2],l+="=");k.src="data:audio/x-"+d.slice(-3)+";base64,"+l;f(k)}};k.src=h;fe(()=>{f(k)})})});var b=n.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),n.elementPointerLock&&b.addEventListener("click",
c=>{!ie&&n.canvas.requestPointerLock&&(n.canvas.requestPointerLock(),c.preventDefault())},!1))}}function le(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var me={},ke,ne={},Wc={get(a,b){var c=ne[b];c||=ne[b]=new WebAssembly.Global({value:"i32",mutable:!0},-1);a.has(b)||(c.required=!0);return c}},y,F,H,x,La,Ma,E,G,Na,A,oe=[];function Ba(a){var b=G[a+48>>2];ud(b,b-G[a+52>>2]);vd(b)}
var pe=new TextDecoder,qe=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},re=(a,b=0,c)=>{c=qe(a,b,c);return pe.decode(a.buffer?a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c):new Uint8Array(a.slice(b,c)))},Yc=a=>{function b(){for(var q=0,t=1;;){var p=a[f++];q+=(p&127)*t;t*=128;if(!(p&128))break}return q}function c(){var q=b();f+=q;return re(a,f-q,q)}function d(){for(var q=b(),t=[];q--;)t.push(c());return t}function e(q,t){if(q)throw Error(t);}var f=0,g=0;if(a instanceof
WebAssembly.Module)g=WebAssembly.Module.customSections(a,"dylink.0"),e(g.length===0,"need dylink section"),a=new Uint8Array(g[0]),g=a.length;else{g=(new Uint32Array((new Uint8Array(a.subarray(0,24))).buffer))[0]==1836278016;e(!g,"need to see wasm magic number");e(a[8]!==0,"need the dylink section to be first");f=9;g=b();g=f+g;var h=c();e(h!=="dylink.0")}for(h={Oa:[],sb:new Set,wb:new Set,pb:[]};f<g;){var k=a[f++],l=b();if(k===1)h.Na=b(),h.ac=b(),h.ua=b(),h.Uc=b();else if(k===2)h.Oa=d();else if(k===
3)for(k=b();k--;){l=c();var m=b();m&256&&h.sb.add(l)}else if(k===4)for(k=b();k--;)c(),l=c(),m=b(),(m&3)==1&&h.wb.add(l);else k===5?h.pb=d():f+=l}return h},Ga=(a,b)=>{de=N=0;jd();a=M.get(a)(b);de||N>0?qa=a:rd(a)},Dd=(a,b,c)=>{c={Ba:Infinity,name:a,exports:c,global:!0};se[a]=c;b!=void 0&&(te[b]=c);return c},se={},te={},ue=(a,b)=>Math.ceil(a/b)*b,ve=a=>{if(Ja)return cd(a,1);var b=Bd;Bd=a=b+Math.ceil(a/16)*16;if(!r){var c=td();G[c>>2]=a}return b},xe=(a,b)=>{if(we)for(var c=a;c<a+b;c++){var d=M.get(c);
d&&we.set(d,c)}},we,ye=a=>{we||(we=new WeakMap,xe(0,M.length));return we.get(a)||0},ze=[],Ae=a=>{var b=a.length;return[b%128|128,b>>7,...a]},Be={i:127,p:127,j:126,f:125,d:124,e:111},Ce=a=>Ae(Array.from(a,b=>Be[b])),De=(a,b)=>{var c=ye(a);if(c)return c;c=ze.length?ze.pop():M.grow(1);try{M.set(c,a)}catch(d){if(!(d instanceof TypeError))throw d;b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...Ae([1,96,...Ce(b.slice(1)),...Ce(b[0]==="v"?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;M.set(c,b)}we.set(a,c);return c},Cd=(a,b)=>{for(var c in a){var d=c;if(!"memory __memory_base __table_base __stack_pointer __indirect_function_table __cpp_exception __c_longjmp __wasm_apply_data_relocs __dso_handle __tls_size __tls_align __set_stack_limits _emscripten_tls_init __wasm_init_tls __wasm_call_ctors __start_em_asm __stop_em_asm __start_em_js __stop_em_js".split(" ").includes(d)&&!d.startsWith("__em_js__")){d=a[c];var e=ne[c]&&ne[c].value!=
-1;if(b||!e){if(typeof d=="function")d=De(d);else if(typeof d.value!="number")continue;let f;ne[f=c]??(ne[f]=new WebAssembly.Global({value:"i32",mutable:!0}));ne[c].value=d}}}},Ee=(a,b=0)=>{var c={},d;for(d in a){var e=d;var f=a[d];a:{if(f instanceof WebAssembly.Global)try{f.value=f.value}catch{var g=!0;break a}g=!1}f=g?new WebAssembly.Global({value:"i32"},f.value+b):f;c[e]=f}return c},Fe=a=>{a=J[a];return!a||a.Ca?!1:!0},Ge=(a,b)=>Object.defineProperty(b,"name",{value:a}),He=a=>{var b;Fe(a)&&(b=J[a]);
return{Ta:b,name:a}},Sa=[],P=(a,b,c)=>a?pe.decode(A.slice(a,qe(A,a,b,c))):"",Me=(a,b,c,d,e)=>{function f(){function k(B,z){function C(ua,Y){ua=[];for(var vb=0;;vb++){var Xa="$"+vb;if(!Y.includes(Xa))break;ua.push(Xa)}ua=ua.join(",");Ie[D]=eval(`(${ua}) => { ${Y} };`)}function K(ua,Y,vb){var Xa=[];Y=Y.slice(1,-1);if(Y!="void"){Y=Y.split(",");for(var Ag of Y)Y=Ag.split(" ").pop(),Xa.push(Y.replaceAll("*",""))}p[ua]=eval(`(${Xa}) => ${vb};`)}!r&&c&&(ta[c]=B);xe(t,g.ua);p=Ee(z.exports,q);Cd(p);b.Ab||
Je();if("__start_em_asm"in p){var D=p.__start_em_asm.value;for(B=p.__stop_em_asm.value;D<B;){var ka=P(D);C(D,ka);D=A.indexOf(0,D)+1}}for(var wb in p)wb.startsWith("__em_js__")&&(D=p[wb].value,ka=P(D),[B,ka]=ka.split("<::>"),K(wb.replace("__em_js__",""),B,ka),delete p[wb]);Zc(p._emscripten_tls_init,z.exports,g);l&&((z=p.__wasm_apply_data_relocs)&&(Ja?z():Oa.push(z)),(z=p.__wasm_call_ctors)&&(Ja?z():Sa.push(z)));return p}var l=!e||!x[e+8];if(l){var m=Math.pow(2,g.ac),q=g.Na?ue(ve(g.Na+m),m):0,t=g.ua?
M.length:0;e&&(x[e+8]=1,G[e+12>>2]=q,F[e+16>>2]=g.Na,G[e+20>>2]=t,F[e+24>>2]=g.ua)}else q=G[e+12>>2],t=G[e+20>>2];g.ua&&M.grow(g.ua);var p;m=new Proxy({},{get(B,z){switch(z){case "__memory_base":return q;case "__table_base":return t}if(z in J&&!J[z].Ca)return J[z];if(!(z in B)){var C;B[z]=(...K)=>{if(!C){var D=He(z).Ta;!D&&d&&(D=d[z]);D||=p[z];C=D}return C(...K)}}return B[z]}});var u=new Proxy(g.wb,Wc),v={"GOT.mem":u,"GOT.func":u,env:m,wasi_snapshot_preview1:m};if(b.J)return(async()=>{var B;a instanceof
WebAssembly.Module?B=new WebAssembly.Instance(a,v):{module:a,instance:B}=await WebAssembly.instantiate(a,v);return k(a,B)})();m=a instanceof WebAssembly.Module?a:new WebAssembly.Module(a);u=new WebAssembly.Instance(m,v);return k(m,u)}var g=Yc(a);b={...b,Sa:{fc:c,kc:g.pb}};if(b.J)return g.Oa.reduce((k,l)=>k.then(()=>{l=Ke(l,b.Sa)??l;return Le(l,b,d)}),Promise.resolve()).then(f);for(var h of g.Oa)h=Ke(h,b.Sa)??h,Le(h,b,d);return f()},Xc=a=>{var b,c;for([b,c]of Object.entries(a))Fe(b)||(J[b]=c)},Ne=
async a=>{a=await ia(a);return new Uint8Array(a)},Oe=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Pe=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=Oe(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Qe=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=
b.slice(0,-1);return a+b},Re=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Se=(a,b)=>Pe(a+"/"+b),Te=a=>{var b=xd();a=a();vd(b);return a},Ue=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},Q=(a,b,c,d)=>{if(!(d>0))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(c>=d)break;b[c++]=g}else if(g<=2047){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(g<=65535){if(c+2>=d)break;b[c++]=224|
g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Ve=a=>{var b=Ue(a)+1,c=wd(b);Q(a,A,c,b);return c},We=()=>a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),0),Xe=a=>(Xe=We())(a),Ye=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:FS.cwd();if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c=c.charAt(0)===
"/"}b=Oe(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ze=(a,b)=>{function c(g){for(var h=0;h<g.length&&g[h]==="";h++);for(var k=g.length-1;k>=0&&g[k]==="";k--);return h>k?[]:g.slice(h,k-h+1)}a=Ye(a).slice(1);b=Ye(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},$e=[],af=a=>{var b=Array(Ue(a)+1);a=Q(a,b,0,b.length);
b.length=a;return b},bf=[];function cf(a,b){bf[a]={input:[],output:[],ea:b};FS.registerDevice(a,df)}
var df={open(a){var b=bf[a.node.sa];if(!b)throw new FS.h(43);a.D=b;a.seekable=!1},close(a){a.D.ea.ya(a.D)},ya(a){a.D.ea.ya(a.D)},read(a,b,c,d){if(!a.D||!a.D.ea.eb)throw new FS.h(60);for(var e=0,f=0;f<d;f++){try{var g=a.D.ea.eb(a.D)}catch(h){throw new FS.h(29);}if(g===void 0&&e===0)throw new FS.h(6);if(g===null||g===void 0)break;e++;b[c+f]=g}e&&(a.node.$=Date.now());return e},write(a,b,c,d){if(!a.D||!a.D.ea.Qa)throw new FS.h(60);try{for(var e=0;e<d;e++)a.D.ea.Qa(a.D,b[c+e])}catch(f){throw new FS.h(29);
}d&&(a.node.P=a.node.O=Date.now());return e}},ef={eb(){a:{if(!$e.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}$e=af(a)}a=$e.shift()}return a},Qa(a,b){b===null||b===10?(la(re(a.output)),a.output=[]):b!=0&&a.output.push(b)},ya(a){a.output?.length>0&&(la(re(a.output)),a.output=[])},Wb(){return{Gc:25856,Ic:5,Fc:191,Hc:35387,Ec:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Xb(){return 0},Yb(){return[24,
80]}},ff={Qa(a,b){b===null||b===10?(w(re(a.output)),a.output=[]):b!=0&&a.output.push(b)},ya(a){a.output?.length>0&&(w(re(a.output)),a.output=[])}},gf=a=>{a=Math.ceil(a/65536)*65536;var b=ed(65536,a);b&&A.fill(0,b,b+a);return b},R={W:null,mount(){return R.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=(c&61440)===4096);if(e)throw new FS.h(63);R.W||(R.W={dir:{node:{S:R.m.S,U:R.m.U,ja:R.m.ja,ca:R.m.ca,rename:R.m.rename,unlink:R.m.unlink,rmdir:R.m.rmdir,ta:R.m.ta,symlink:R.m.symlink},
stream:{llseek:R.o.llseek}},file:{node:{S:R.m.S,U:R.m.U},stream:{llseek:R.o.llseek,read:R.o.read,write:R.o.write,ka:R.o.ka,ma:R.o.ma}},link:{node:{S:R.m.S,U:R.m.U,readlink:R.m.readlink},stream:{}},Wa:{node:{S:R.m.S,U:R.m.U},stream:FS.Db}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.m=R.W.dir.node,c.o=R.W.dir.stream,c.v={}):FS.isFile(c.mode)?(c.m=R.W.file.node,c.o=R.W.file.stream,c.M=0,c.v=R.Ib??(R.Ib=new Uint8Array(0))):FS.isLink(c.mode)?(c.m=R.W.link.node,c.o=R.W.link.stream):FS.isChrdev(c.mode)&&
(c.m=R.W.Wa.node,c.o=R.W.Wa.stream);c.$=c.P=c.O=Date.now();a&&(a.v[b]=c,a.$=a.P=a.O=c.$);return c},m:{S(a){var b={};b.Fb=FS.isChrdev(a.mode)?a.id:1;b.Vb=a.id;b.mode=a.mode;b.bc=1;b.uid=0;b.Rb=0;b.sa=a.sa;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.M:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.$=new Date(a.$);b.P=new Date(a.P);b.O=new Date(a.O);b.Cb=4096;b.Va=Math.ceil(b.size/b.Cb);return b},U(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&
(b=b.size,a.M!=b&&(c=a.v,a.v=new Uint8Array(b),a.v.set(c.subarray(0,Math.min(b,a.M))),a.M=b))},ja(){R.Fa||(R.Fa=new FS.h(44),R.Fa.stack="<generic error, no stack>");throw R.Fa;},ca(a,b,c,d){return R.createNode(a,b,c,d)},rename(a,b,c){try{var d=hf(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.v)throw new FS.h(55);jf(d)}delete a.parent.v[a.name];b.v[c]=a;a.name=c;b.O=b.P=a.parent.O=a.parent.P=Date.now()},unlink(a,b){delete a.v[b];a.O=a.P=Date.now()},rmdir(a,b){var c=hf(a,b),d;for(d in c.v)throw new FS.h(55);
delete a.v[b];a.O=a.P=Date.now()},ta(a){return[".","..",...Object.keys(a.v)]},symlink(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.h(28);return a.link}},o:{read(a,b,c,d,e){if(e>=a.node.M)return 0;d=Math.min(a.node.M-e,d);b.set(a.node.v.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.P=a.O=Date.now();if(f)a.v=b.subarray(c,c+d),a.M=d;else if(a.M===0&&e===0)a.v=b.slice(c,c+d),a.M=d;else{f=e+d;var g=a.v.length;g>=f||(f=
Math.max(f,g*(g<1048576?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.v.subarray(0,a.M),a.v=new Uint8Array(f),a.v.set(g));a.v.set(b.subarray(c,c+d),e);a.M=Math.max(a.M,e+d)}return d},llseek(a,b,c){c===1?b+=a.position:c===2&&FS.isFile(a.node.mode)&&(b+=a.node.M);if(b<0)throw new FS.h(28);return b},ka(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.h(43);a=a.node.v;if(e&2||a.buffer!==x.buffer){d=!0;e=gf(b);if(!e)throw new FS.h(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);x.set(a,e)}}else d=!1,e=a.byteOffset;return{B:e,fa:d}},ma(a,b,c,d){R.o.write(a,b,0,d,c,!1);return 0}}},kf=a=>{typeof a=="string"&&(a=af(a));a.subarray||(a=new Uint8Array(a));return a},lf=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},mf=async(a,b)=>{typeof me!="undefined"&&je();for(var c of ge)if(c.canHandle(b))return c.handle(a,b);return a},nf=async(a,b,c,d,e,f,g,h)=>{var k=b?Ye(Pe(a+"/"+b)):a,l=`cp ${k}`;Td(l);try{var m=c;typeof c=="string"&&(m=await Ne(c));m=await mf(m,k);h?.();f||FS.createDataFile(a,
b,m,d,e,g)}finally{Sd(l)}};function hf(a,b){var c=FS.isDir(a.mode)?(c=of(a,"x"))?c:a.m.ja?0:2:54;if(c)throw new FS.h(c);for(c=FS.da[pf(a.id,b)];c;c=c.la){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.ja(a,b)}function jf(a){var b=pf(a.parent.id,a.name);if(FS.da[b]===a)FS.da[b]=a.la;else for(b=FS.da[b];b;){if(b.la===a){b.la=a.la;break}b=b.la}}function pf(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.da.length}
function qf(a){var b=pf(a.parent.id,a.name);a.la=FS.da[b];FS.da[b]=a}function of(a,b){return FS.fb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function rf(a,b){if(!FS.isDir(a.mode))return 54;try{return hf(a,b),20}catch(c){}return of(a,"wx")}
function sf(a,b,c){try{var d=hf(a,b)}catch(e){return e.C}if(a=of(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.oa(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function tf(a,b){if(!a)throw new FS.h(b);return a}function S(a){a=FS.cb(a);if(!a)throw new FS.h(8);return a}function uf(a,b=-1){a=Object.assign(new FS.yb,a);if(b==-1)a:{for(b=0;b<=FS.zb;b++)if(!FS.streams[b])break a;throw new FS.h(33);}a.aa=b;return FS.streams[b]=a}
function vf(a,b=-1){a=uf(a,b);a.o?.Kc?.(a);return a}function wf(a,b,c){var d=a?.o.U;a=d?a:b;d??=b.m.U;tf(d,63);try{d(a,c)}catch(e){if(e instanceof RangeError)throw new FS.h(22);throw e;}}function xf(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.pa)}return b}function yf(a){var b={Dc:4096,Nc:4096,Va:1E6,Cc:5E5,Bc:5E5,files:FS.Pa,Lc:FS.Pa-1,Oc:42,flags:2,Rc:255};a.m.qb&&Object.assign(b,a.m.qb(a.mount.dc.root));return b}
function zf(a,b,c,d){wf(a,b,{mode:c&4095|b.mode&-4096,O:Date.now(),$a:d})}function Af(a,b,c){if(FS.isDir(b.mode))throw new FS.h(31);if(!FS.isFile(b.mode))throw new FS.h(28);var d=of(b,"w");if(d)throw new FS.h(d);wf(a,b,{size:c,timestamp:Date.now()})}function Bf(a,b,c,d){a=typeof a=="string"?a:FS.getPath(a);b=Pe(a+"/"+b);return FS.create(b,lf(c,d))}
function Cf(a){if(!(a.Zb||a.$b||a.link||a.v))if(globalThis.XMLHttpRequest)I("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.v=ja(a.url)}catch(b){throw new FS.h(29);}}
var FS={root:null,pa:[],Za:{},streams:[],Pa:1,da:null,Xa:"/",Ia:!1,fb:!0,Lb:null,Da:0,h:class{name="ErrnoError";constructor(a){this.C=a}},yb:class{shared={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},xb:class{m={};o={};T=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.Pa++;this.name=b;this.mode=
c;this.sa=d;this.$=this.P=this.O=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:this.mode&=-147}get $b(){return FS.isDir(this.mode)}get Zb(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.h(44);b.xa??(b.xa=!0);a.charAt(0)==="/"||(a=FS.cwd()+"/"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(h=>!!h);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-
1;if(g&&b.parent)break;if(a[f]!==".")if(a[f]==="..")if(e=Qe(e),FS.oa(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Pe(e+"/"+a[f]);try{d=hf(d,a[f])}catch(h){if(h?.C===44&&g&&b.cc)return{path:e};throw h;}!d.T||g&&!b.xa||(d=d.T.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.m.readlink)throw new FS.h(52);d=d.m.readlink(d);d.charAt(0)==="/"||(d=Qe(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.h(32);},getPath(a){for(var b;;){if(FS.oa(a))return a=
a.mount.jb,b?a[a.length-1]!=="/"?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.xb(a,b,c,d);qf(a);return a},oa(a){return a===a.parent},isFile(a){return(a&61440)===32768},isDir(a){return(a&61440)===16384},isLink(a){return(a&61440)===40960},isChrdev(a){return(a&61440)===8192},isBlkdev(a){return(a&61440)===24576},isSocket(a){return(a&49152)===49152},zb:4096,cb:a=>FS.streams[a],Db:{open(a){a.o=FS.Nb(a.node.sa).o;a.o.open?.(a)},llseek(){throw new FS.h(70);}},Ma:a=>
a>>8,Pc:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.Za[a]={o:b}},Nb:a=>FS.Za[a],syncfs(a,b){function c(h){FS.Da--;return b(h)}function d(h){if(h){if(!d.Jb)return d.Jb=!0,c(h)}else++f>=e.length&&c(null)}typeof a=="function"&&(b=a,a=!1);FS.Da++;FS.Da>1&&w(`warning: ${FS.Da} FS.syncfs operations in flight at once, probably just doing extra work`);var e=xf(FS.root.mount),f=0,g;for(g of e)g.type.syncfs?g.type.syncfs(g,a,d):d(null)},mount(a,b,c){var d=c==="/";if(d&&FS.root)throw new FS.h(10);
if(!d&&c){var e=FS.lookupPath(c,{xa:!1});c=e.path;e=e.node;if(e.T)throw new FS.h(10);if(!FS.isDir(e.mode))throw new FS.h(54);}b={type:a,dc:b,jb:c,pa:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.T=b,e.mount&&e.mount.pa.push(b));return a},unmount(a){a=FS.lookupPath(a,{xa:!1});if(!a.node.T)throw new FS.h(28);a=a.node;var b=a.T,c=xf(b);for([,e]of Object.entries(FS.da))for(;e;){var d=e.la;c.includes(e.mount)&&jf(e);var e=d}a.T=null;a.mount.pa.splice(a.mount.pa.indexOf(b),1)},ja(a,b){return a.m.ja(a,
b)},ca(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=Re(a);if(!a)throw new FS.h(28);if(a==="."||a==="..")throw new FS.h(20);var e=rf(d,a);if(e)throw new FS.h(e);if(!d.m.ca)throw new FS.h(63);return d.m.ca(d,a,b,c)},qb(a){return yf(FS.lookupPath(a,{follow:!0}).node)},Tc(a){return yf(a.node)},create(a,b=438){return FS.ca(a,b&4095|32768,0)},mkdir(a,b=511){return FS.ca(a,b&1023|16384,0)},Qc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||a.charAt(0)==="/")d+="/";d+=e;try{FS.mkdir(d,b)}catch(f){if(f.C!=
20)throw f;}}},mkdev(a,b,c){typeof c=="undefined"&&(c=b,b=438);return FS.ca(a,b|8192,c)},symlink(a,b){if(!Ye(a))throw new FS.h(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.h(44);b=Re(b);var d=rf(c,b);if(d)throw new FS.h(d);if(!c.m.symlink)throw new FS.h(63);return c.m.symlink(c,b,a)},rename(a,b){var c=Qe(a),d=Qe(b),e=Re(a),f=Re(b);var g=FS.lookupPath(a,{parent:!0});var h=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!h||!g)throw new FS.h(44);if(h.mount!==g.mount)throw new FS.h(75);
var k=hf(h,e);a=Ze(a,d);if(a.charAt(0)!==".")throw new FS.h(28);a=Ze(b,c);if(a.charAt(0)!==".")throw new FS.h(55);try{var l=hf(g,f)}catch(m){}if(k!==l){b=FS.isDir(k.mode);if(e=sf(h,e,b))throw new FS.h(e);if(e=l?sf(g,f,b):rf(g,f))throw new FS.h(e);if(!h.m.rename)throw new FS.h(63);if(k.T||l&&l.T)throw new FS.h(10);if(g!==h&&(e=of(h,"w")))throw new FS.h(e);jf(k);try{h.m.rename(k,g,f),k.parent=g}catch(m){throw m;}finally{qf(k)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=Re(a);var c=hf(b,a),
d=sf(b,a,!0);if(d)throw new FS.h(d);if(!b.m.rmdir)throw new FS.h(63);if(c.T)throw new FS.h(10);b.m.rmdir(b,a);jf(c)},ta(a){a=FS.lookupPath(a,{follow:!0}).node;return tf(a.m.ta,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.h(44);a=Re(a);var c=hf(b,a),d=sf(b,a,!1);if(d)throw new FS.h(d);if(!b.m.unlink)throw new FS.h(63);if(c.T)throw new FS.h(10);b.m.unlink(b,a);jf(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.h(44);if(!a.m.readlink)throw new FS.h(28);return a.m.readlink(a)},
stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return tf(a.m.S,63)(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a=typeof a=="string"?FS.lookupPath(a,{follow:!c}).node:a;zf(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=S(a);zf(a,a.node,b,!1)},chown(a,b,c,d){a=typeof a=="string"?FS.lookupPath(a,{follow:!d}).node:a;wf(null,a,{timestamp:Date.now(),$a:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=S(a);wf(a,a.node,{timestamp:Date.now(),$a:!1})},truncate(a,b){if(b<0)throw new FS.h(28);
a=typeof a=="string"?FS.lookupPath(a,{follow:!0}).node:a;Af(null,a,b)},ftruncate(a,b){a=S(a);if(b<0||(a.flags&2097155)===0)throw new FS.h(28);Af(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;tf(a.m.U,63)(a,{$:b,P:c})},open(a,b,c=438){if(a==="")throw new FS.h(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");
var f=FS.lookupPath(a,{follow:!(b&131072),cc:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new FS.h(20);}else{if(e)throw new FS.h(31);d=FS.ca(a,c|511,0);f=!0}if(!d)throw new FS.h(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.h(54);if(!f){e=d;a=b;if(e)if(FS.isLink(e.mode))e=32;else{var g=["r","w","rw"][a&3];a&512&&(g+="w");e=FS.isDir(e.mode)&&(g!=="r"||a&576)?31:of(e,g)}else e=44;if(e)throw new FS.h(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;b=uf({node:d,
path:FS.getPath(d),flags:b,seekable:!0,position:0,o:d.o,xc:[],error:!1});b.o.open&&b.o.open(b);f&&FS.chmod(d,c&511);return b},close(a){if(a.aa===null)throw new FS.h(8);a.Ga&&(a.Ga=null);try{a.o.close&&a.o.close(a)}catch(b){throw b;}finally{FS.streams[a.aa]=null}a.aa=null},llseek(a,b,c){if(a.aa===null)throw new FS.h(8);if(!a.seekable||!a.o.llseek)throw new FS.h(70);if(c!=0&&c!=1&&c!=2)throw new FS.h(28);a.position=a.o.llseek(a,b,c);a.xc=[];return a.position},read(a,b,c,d,e){if(d<0||e<0)throw new FS.h(28);
if(a.aa===null)throw new FS.h(8);if((a.flags&2097155)===1)throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.read)throw new FS.h(28);var f=typeof e!="undefined";if(!f)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(d<0||e<0)throw new FS.h(28);if(a.aa===null)throw new FS.h(8);if((a.flags&2097155)===0)throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.write)throw new FS.h(28);a.seekable&&
a.flags&1024&&FS.llseek(a,0,2);var g=typeof e!="undefined";if(!g)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.write(a,b,c,d,e,f);g||(a.position+=b);return b},ka(a,b,c,d,e){if((d&2)!==0&&(e&2)===0&&(a.flags&2097155)!==2)throw new FS.h(2);if((a.flags&2097155)===1)throw new FS.h(2);if(!a.o.ka)throw new FS.h(43);if(!b)throw new FS.h(28);return a.o.ka(a,b,c,d,e)},ma(a,b,c,d,e){return a.o.ma?a.o.ma(a,b,c,d,e):0},Ja(a,b,c){if(!a.o.Ja)throw new FS.h(59);return a.o.Ja(a,b,c)},readFile(a,b={}){b.flags=
b.flags??0;b.encoding=b.encoding??"binary";b.encoding!=="utf8"&&b.encoding!=="binary"&&I(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);b.encoding==="utf8"&&(d=re(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags??577;a=FS.open(a,c.flags,c.mode);b=kf(b);FS.write(a,b,0,b.byteLength,void 0,c.Jc);FS.close(a)},cwd:()=>FS.Xa,chdir(a){a=FS.lookupPath(a,{follow:!0});if(a.node===null)throw new FS.h(44);if(!FS.isDir(a.node.mode))throw new FS.h(54);
var b=of(a.node,"x");if(b)throw new FS.h(b);FS.Xa=a.path},init(a,b,c){FS.Ia=!0;a??=n.stdin;b??=n.stdout;c??=n.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Mc(a,b){a=FS.analyzePath(a,b);return a.ab?a.object:null},analyzePath(a,b){try{var c=
FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={oa:!1,ab:!1,error:0,name:null,path:null,object:null,ec:!1,jc:null,hc:null};try{c=FS.lookupPath(a,{parent:!0}),d.ec=!0,d.jc=c.path,d.hc=c.node,d.name=Re(a),c=FS.lookupPath(a,{follow:!b}),d.ab=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.oa=c.path==="/"}catch(e){d.error=e.C}return d},createPath(a,b){a=typeof a=="string"?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Pe(a+"/"+c);try{FS.mkdir(d)}catch(e){if(e.C!=
20)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a=typeof a=="string"?a:FS.getPath(a),g=b?Pe(a+"/"+b):a);a=lf(d,e);g=FS.create(g,a);c&&(c=kf(c),FS.chmod(g,a|146),b=FS.open(g,577),FS.write(b,c,0,c.length,0,f),FS.close(b),FS.chmod(g,a))},createDevice(a,b,c,d){a=Se(typeof a=="string"?a:FS.getPath(a),b);b=lf(!!c,!!d);var e;(e=FS.createDevice).Ma??(e.Ma=64);e=FS.makedev(FS.createDevice.Ma++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,h,k){for(var l=
0,m=0;m<k;m++){try{var q=c()}catch(t){throw new FS.h(29);}if(q===void 0&&l===0)throw new FS.h(6);if(q===null||q===void 0)break;l++;g[h+m]=q}l&&(f.node.$=Date.now());return l},write(f,g,h,k){for(var l=0;l<k;l++)try{d(g[h+l])}catch(m){throw new FS.h(29);}k&&(f.node.P=f.node.O=Date.now());return l}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(m,q,t,p,u){m=m.node.v;if(u>=m.length)return 0;p=Math.min(m.length-u,p);if(m.slice)for(var v=0;v<p;v++)q[t+v]=m[u+v];else for(v=0;v<p;v++)q[t+
v]=m.get(u+v);return p}class g{Ha=!1;ia=[];na=void 0;ib=0;hb=0;get(m){if(!(m>this.length-1||m<0)){var q=m%this.tb;return this.na(m/this.tb|0)[q]}}yc(m){this.na=m}kb(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);m.status>=200&&m.status<300||m.status===304||I("Couldn't load "+c+". Status: "+m.status);var q=Number(m.getResponseHeader("Content-length")),t,p=(t=m.getResponseHeader("Accept-Ranges"))&&t==="bytes";m=(t=m.getResponseHeader("Content-Encoding"))&&t==="gzip";var u=1048576;p||(u=
q);var v=this;v.yc(B=>{var z=B*u,C=(B+1)*u-1;C=Math.min(C,q-1);if(typeof v.ia[B]=="undefined"){var K=v.ia;z>C&&I(`invalid range (${z}, ${C}) or no bytes requested!`);C>q-1&&I(`only ${q} bytes available! programmer error!`);var D=new XMLHttpRequest;D.open("GET",c,!1);q!==u&&D.setRequestHeader("Range","bytes="+z+"-"+C);D.responseType="arraybuffer";D.overrideMimeType&&D.overrideMimeType("text/plain; charset=x-user-defined");D.send(null);D.status>=200&&D.status<300||D.status===304||I("Couldn't load "+
c+". Status: "+D.status);z=D.response!==void 0?new Uint8Array(D.response||[]):af(D.responseText??"");K[B]=z}typeof v.ia[B]=="undefined"&&I("doXHR failed!");return v.ia[B]});if(m||!q)u=q=1,u=q=this.na(0).length,la("LazyFiles on gzip forces download of the whole file when length is accessed");this.ib=q;this.hb=u;this.Ha=!0}get length(){this.Ha||this.kb();return this.ib}get tb(){this.Ha||this.kb();return this.hb}}if(globalThis.XMLHttpRequest){ba||I("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var h=new g;var k=void 0}else k=c,h=void 0;var l=Bf(a,b,d,e);h?l.v=h:k&&(l.v=null,l.url=k);Object.defineProperties(l,{M:{get:function(){return this.v.length}}});a={};for(let [m,q]of Object.entries(l.o))a[m]=(...t)=>{Cf(l);return q(...t)};a.read=(m,q,t,p,u)=>{Cf(l);return f(m,q,t,p,u)};a.ka=(m,q,t)=>{Cf(l);var p=gf(q);if(!p)throw new FS.h(48);f(m,x,p,q,t);return{B:p,fa:!0}};l.o=a;return l}},Ke=(a,b)=>{if(Ja){if(a.charAt(0)==="/")try{return FS.lookupPath(a),a}catch(d){return}var c=(b?.kc||[]).map(d=>
{var e=b?.fc;return d.startsWith("$ORIGIN")?d.replace("$ORIGIN",Qe(e)):d});return Te(()=>{var d=wd(512),e=Ve(c.join(":")),f=Ve(a);return(d=md(d,e,f,512))?P(d):void 0})}};
function Le(a,b={global:!0,qa:!0},c,d){function e(){var k=ta[a];if(k)return b.J?Promise.resolve(k):k;if(d){k=G[d+28>>2];var l=G[d+32>>2];if(k&&l)return k=x.slice(k,k+l),b.J?Promise.resolve(k):k}if(k=Ke(a,b.Sa))return k=FS.readFile(k,{encoding:"binary"}),b.J?Promise.resolve(k):k;k=ha(a);if(b.J)return Ne(k);if(!ja)throw Error(`${k}: file not found, and synchronous loading of external files is not available`);return ja(k)}function f(){var k=he[a];return k?b.J?Promise.resolve(k):k:b.J?e().then(l=>Me(l,
b,a,c,d)):Me(e(),b,a,c,d)}function g(k){h.global?Xc(k):c&&Object.assign(c,k);h.exports=k}var h=se[a];if(h)return b.global?h.global||(h.global=!0,Xc(h.exports)):c&&Object.assign(c,h.exports),b.qa&&h.Ba!==Infinity&&(h.Ba=Infinity),h.Ba++,d&&(te[d]=h),b.J?Promise.resolve(!0):!0;h=Dd(a,d,"loading");h.Ba=b.qa?Infinity:1;h.global=b.global;if(b.J)return f().then(k=>{g(k);return!0});g(f());return!0}
var Je=()=>{var a,b;for([a,b]of Object.entries(ne))if(b.value==-1){var c=He(a).Ta;if(c||b.required)if(typeof c=="function")b.value=De(c,c.g);else if(typeof c=="number")b.value=c;else if(typeof c.value=="number")b.value=c;else throw Error(`bad export type for '${a}': ${typeof c} (${c})`);else b.value=0}},Ed=async()=>{if(ma.length){Td("loadDylibs");for(var a of ma)await Le(a,{J:!0,global:!0,qa:!0,Ab:!0});Je();Sd("loadDylibs")}else Je()},de=!1,Zc=(a,b,c)=>{function d(){var e=a();if(e){var f={};c.sb.forEach(g=>
f[g]=b[g]);Cd(Ee(f,e),!0)}}Yd.push(d);Ja&&d()},xa,$a=(a,b,c,d)=>I(`Assertion failed: ${P(a)}, at: `+[b?P(b):"unknown filename",c,d?P(d):"unknown function"]);$a.g="vppip";var ab=(a,b)=>M.get(a)(b);ab.g="vpi";function bb(...a){return J.__lsan_ignore_object(...a)}bb.Ca=!0;function Df(a,b,c,d){return r?O(2,1,a,b,c,d):cb(a,b,c,d)}var cb=(a,b,c,d)=>{if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(r&&e.length===0)return Df(a,b,c,d);a={uc:c,X:a,Ea:d,wc:e};return r?(a.V=5,postMessage(a,e),0):Wd(a)};
cb.g="ipppp";var Ef=18;function Ff(a,b,c){if(b.charAt(0)==="/")return b;a=a===-100?FS.cwd():S(a).path;if(b.length==0){if(!c)throw new FS.h(44);return a}return a+"/"+b}
function Gf(a,b){G[a>>2]=b.Fb;G[a+4>>2]=b.mode;G[a+8>>2]=b.bc;G[a+12>>2]=b.uid;G[a+16>>2]=b.Rb;G[a+20>>2]=b.sa;H[a+24>>3]=BigInt(b.size);F[a+32>>2]=4096;F[a+36>>2]=b.Va;var c=b.$.getTime(),d=b.P.getTime(),e=b.O.getTime();H[a+40>>3]=BigInt(Math.floor(c/1E3));G[a+48>>2]=c%1E3*1E3*1E3;H[a+56>>3]=BigInt(Math.floor(d/1E3));G[a+64>>2]=d%1E3*1E3*1E3;H[a+72>>3]=BigInt(Math.floor(e/1E3));G[a+80>>2]=e%1E3*1E3*1E3;H[a+88>>3]=BigInt(b.Vb);return 0}var Hf=void 0;
function db(a){if(r)return O(3,1,a);try{var b=S(a);return vf(b).aa}catch(c){if(typeof FS=="undefined"||c.name!=="ErrnoError")throw c;return-c.C}}db.g="ii";function eb(a,b,c,d){if(r)return O(4,1,a,b,c,d);try{b=P(b);b=Ff(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&of(e,a)?-2:0}catch(f){if(typeof FS=="undefined"||f.name!=="ErrnoError")throw f;return-f.C}}eb.g="iipii";var If=()=>{var a=F[+Hf>>2];Hf+=4;return a};
function fb(a,b,c){if(r)return O(5,1,a,b,c);Hf=c;try{var d=S(a);switch(b){case 0:var e=If();if(e<0)break;for(;FS.streams[e];)e++;return vf(d,e).aa;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=If(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=If(),y[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if(typeof FS=="undefined"||f.name!=="ErrnoError")throw f;return-f.C}}fb.g="iiip";
function gb(a,b){if(r)return O(6,1,a,b);try{var c=S(a),d=c.node,e=c.o.S;a=e?c:d;e??=d.m.S;tf(e,63);var f=e(a);return Gf(b,f)}catch(g){if(typeof FS=="undefined"||g.name!=="ErrnoError")throw g;return-g.C}}gb.g="iip";function hb(a,b){if(r)return O(7,1,a,b);b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return-22;FS.ftruncate(a,b);return 0}catch(c){if(typeof FS=="undefined"||c.name!=="ErrnoError")throw c;return-c.C}}hb.g="iij";
function ib(a,b){if(r)return O(8,1,a,b);try{if(b===0)return-28;var c=FS.cwd(),d=Ue(c)+1;if(b<d)return-68;Q(c,A,a,b);return d}catch(e){if(typeof FS=="undefined"||e.name!=="ErrnoError")throw e;return-e.C}}ib.g="ipp";
function jb(a,b,c){if(r)return O(9,1,a,b,c);Hf=c;try{var d=S(a);switch(b){case 21509:return d.D?0:-59;case 21505:if(!d.D)return-59;if(d.D.ea.Wb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=If();F[e>>2]=25856;F[e+4>>2]=5;F[e+8>>2]=191;F[e+12>>2]=35387;for(var f=0;f<32;f++)x[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.D?0:-59;case 21506:case 21507:case 21508:if(!d.D)return-59;if(d.D.ea.Xb)for(e=If(),a=[],f=0;f<32;f++)a.push(x[e+f+17]);
return 0;case 21519:if(!d.D)return-59;e=If();return F[e>>2]=0;case 21520:return d.D?-28:-59;case 21537:case 21531:return e=If(),FS.Ja(d,b,e);case 21523:if(!d.D)return-59;d.D.ea.Yb&&(f=[24,80],e=If(),y[e>>1]=f[0],y[e+2>>1]=f[1]);return 0;case 21524:return d.D?0:-59;case 21515:return d.D?0:-59;default:return-28}}catch(g){if(typeof FS=="undefined"||g.name!=="ErrnoError")throw g;return-g.C}}jb.g="iiip";
function kb(a,b){if(r)return O(10,1,a,b);try{return a=P(a),Gf(b,FS.lstat(a))}catch(c){if(typeof FS=="undefined"||c.name!=="ErrnoError")throw c;return-c.C}}kb.g="ipp";function lb(a,b,c,d){if(r)return O(11,1,a,b,c,d);try{b=P(b);var e=d&256;b=Ff(a,b,d&4096);return Gf(c,e?FS.lstat(b):FS.stat(b))}catch(f){if(typeof FS=="undefined"||f.name!=="ErrnoError")throw f;return-f.C}}lb.g="iippi";
function mb(a,b,c,d){if(r)return O(12,1,a,b,c,d);Hf=d;try{b=P(b);b=Ff(a,b);var e=d?If():0;c&64&&(e&=~Ef);return FS.open(b,c,e).aa}catch(f){if(typeof FS=="undefined"||f.name!=="ErrnoError")throw f;return-f.C}}mb.g="iipip";
function nb(a,b,c){if(r)return O(13,2,a,b,c);try{let u=ce;var d,e=new Promise(z=>{d=z}),f=[],g=!1;function v(z){g||(g=!0,f.forEach(C=>C()),d(z))}function B(z,C){return K=>{g||(K&=y[C+4>>1]|24,y[C+6>>1]=K,v(1))}}if(u&&c>0){var h=setTimeout(()=>{v(0)},c);f.push(()=>clearTimeout(h))}for(var k=0,l=0;l<b;l++){var m=a+8*l,q=y[m+4>>1],t=32,p=FS.cb(F[m>>2]);p&&(p.o.lb?t=u&&c?p.o.lb(p,c,B(p,m)):p.o.lb(p,-1):t=5);(t&=q|24)&&k++;y[m+6>>1]=t}return u?(!k&&c||v(k),e):k}catch(u){if(typeof FS=="undefined"||u.name!==
"ErrnoError")throw u;return-u.C}}nb.g="ipii";function ob(a){if(r)return O(14,1,a);try{return a=P(a),FS.rmdir(a),0}catch(b){if(typeof FS=="undefined"||b.name!=="ErrnoError")throw b;return-b.C}}ob.g="ip";function pb(a,b){if(r)return O(15,1,a,b);try{return a=P(a),Gf(b,FS.stat(a))}catch(c){if(typeof FS=="undefined"||c.name!=="ErrnoError")throw c;return-c.C}}pb.g="ipp";
function qb(a,b,c){if(r)return O(16,1,a,b,c);try{b=P(b);b=Ff(a,b);if(c)if(c===512)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if(typeof FS=="undefined"||d.name!=="ErrnoError")throw d;return-d.C}}qb.g="iipi";var rb=a=>{a=new WebAssembly.Exception(Ad,[a],{traceStack:!0});var b=a.getArg(Ad,0);var c=yd(b);b=xd();var d=wd(4),e=wd(4);zd(c,d,e);c=G[d>>2];e=G[e>>2];d=P(c);L(c);if(e){var f=P(e);L(e)}vd(b);a.message=[d,f];throw a;},sb=()=>I("");sb.g="v";
var Jf=a=>{var b=xd();a=Ve(a);gd(a,0);vd(b)},Kf=(a,b)=>{var c=P(a+36),d=F[a+4>>2];c=Pe(c);var e=!!(d&256),f=e?null:{};d={global:e,qa:!!(d&4096),J:b.J};if(b.J)return Le(c,d,f,a);try{return Le(c,d,f,a)}catch(g){return Jf(`could not load dynamic lib: ${c}\n${g}`),0}},tb=a=>Kf(a,{J:!1});tb.g="pp";var ub=(a,b)=>{a=te[a].exports;b=Object.keys(a)[b];b=a[b];return De(b,b.g)};ub.g="ppi";
var xb=(a,b,c)=>{b=P(b);var d=te[a];a=Object.keys(d.exports).indexOf(b);if(a==-1||d.exports[b].Ca)return Jf(`Tried to lookup unknown symbol "${b}" in dynamic lib: ${d.name}`),0;b=d.exports[b];typeof b=="function"&&((d=ye(b))?b=d:(b=De(b,b.g),G[c>>2]=a));return b};xb.g="pppp";var Lf={},Mf=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Nf(a){return this.A(G[a>>2])}
var Of={},Pf={},Qf={},Rf=class extends Error{constructor(a){super(a);this.name="InternalError"}},U=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new Rf("Mismatched type converter count");for(var k=0;k<a.length;++k)T(a[k],h[k])}a.forEach(h=>Qf[h]=b);var e=Array(b.length),f=[],g=0;for(let [h,k]of b.entries())Pf.hasOwnProperty(k)?e[h]=Pf[k]:(f.push(k),Of.hasOwnProperty(k)||(Of[k]=[]),Of[k].push(()=>{e[h]=Pf[k];++g;g===f.length&&d(e)}));0===f.length&&d(e)},yb=a=>{var b=Lf[a];delete Lf[a];
var c=b.Ra,d=b.Y,e=b.bb,f=e.map(g=>g.Qb).concat(e.map(g=>g.qc));U([a],f,g=>{var h={},k,l;for([k,l]of e.entries()){let m=g[k],q=l.na,t=l.Pb,p=g[k+e.length],u=l.oc,v=l.rc;h[l.Kb]={read:B=>m.A(q(t,B)),write:(B,z)=>{var C=[];u(v,B,p.G(C,z));Mf(C)},optional:m.optional}}return[{name:b.name,A:m=>{var q={},t;for(t in h)q[t]=h[t].read(m);d(m);return q},G:(m,q)=>{for(var t in h)if(!(t in q||h[t].optional))throw new TypeError(`Missing field: "${t}"`);var p=c();for(t in h)h[t].write(p,q[t]);m!==null&&m.push(d,
p);return p},L:Nf,I:d}]})};yb.g="vp";var V=a=>{for(var b="";;){var c=A[a++];if(!c)return b;b+=String.fromCharCode(c)}},W=class extends Error{constructor(a){super(a);this.name="BindingError"}},Sf=a=>{throw new W(a);};
function Tf(a,b,c={}){var d=b.name;if(!a)throw new W(`type "${d}" must have a positive integer typeid pointer`);if(Pf.hasOwnProperty(a)){if(c.Ub)return;throw new W(`Cannot register type '${d}' twice`);}Pf[a]=b;delete Qf[a];Of.hasOwnProperty(a)&&(b=Of[a],delete Of[a],b.forEach(e=>e()))}function T(a,b,c={}){return Tf(a,b,c)}
var zb=(a,b,c,d,e)=>{b=V(b);if(d)a:switch(c){case 4:d=La;break a;case 8:d=Ma;break a;default:throw new TypeError(`invalid float width (${c}): ${b}`);}else a:switch(c){case 1:d=e?x:A;break a;case 2:d=e?y:E;break a;case 4:d=e?F:G;break a;case 8:d=e?H:Na;break a;default:throw new TypeError(`invalid integer width (${c}): ${b}`);}var f=d,g=Math.log2(c);T(a,{name:b,A:h=>{var k=h+Math.max(4,c)>>g;k=Array.from(f.subarray(k,k+G[h>>2]));L(h);return k},G:(h,k)=>{typeof k=="number"&&(k=[k]);if(!Array.isArray(k))throw new W(`Cannot pass non-array to C++ vector type ${b}`);
k=Array.prototype.concat.apply([],k);var l=k.length,m=Math.max(4,c),q=ad(m+l*c);m=q+m>>g;G[q>>2]=l;f.set(k,m);h!==null&&h.push(L,q);return q},L:Nf,I(h){L(h)}})};zb.g="vpppii";
var Uf=(a,b,c)=>{switch(b){case 1:return c?d=>x[d]:d=>A[d];case 2:return c?d=>y[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];case 8:return c?d=>H[d>>3]:d=>Na[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ab=(a,b,c,d,e)=>{b=V(b);d=d===0n;var f=g=>g;if(d){let g=c*8;f=h=>BigInt.asUintN(g,h);e=f(e)}T(a,{name:b,A:f,G:(g,h)=>{typeof h=="number"&&(h=BigInt(h));return h},L:Uf(b,c,!d),I:null})};Ab.g="vpppjj";
var Bb=(a,b,c,d)=>{b=V(b);T(a,{name:b,A:function(e){return!!e},G:function(e,f){return f?c:d},L:function(e){return this.A(A[e])},I:null})};Bb.g="vppii";
var Vf=a=>{throw new W(a.l.F.u.name+" instance already deleted");},Wf=!1,Xf=!1,Yf=()=>{},Zf=a=>{if(Wf)return Zf=b=>b.deleteLater(),Zf(a);if(!globalThis.FinalizationRegistry)return Zf=b=>b,a;Xf=new FinalizationRegistry(b=>{b=b.l;--b.count.value;0===b.count.value&&(b.K?b.R.Y(b.K):b.F.u.Y(b.B))});Zf=b=>{var c=b.l;c.K&&Xf.register(b,{l:c},b);return b};Yf=b=>{Xf.unregister(b)};return Zf(a)},$f=[],ag=()=>{for(;$f.length;){var a=$f.pop();a.l.ha=!1;a["delete"]()}},bg;function cg(){}
var dg={},eg=(a,b,c)=>{if(void 0===a[b].H){var d=a[b];a[b]=function(...e){if(!a[b].H.hasOwnProperty(e.length))throw new W(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].H})!`);return a[b].H[e.length].apply(this,e)};a[b].H=[];a[b].H[d.Z]=d}},fg=(a,b,c)=>{if(n.hasOwnProperty(a)){if(void 0===c||void 0!==n[a].H&&void 0!==n[a].H[c])throw new W(`Cannot register public name '${a}' twice`);eg(n,a,a);if(n[a].H.hasOwnProperty(c))throw new W(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
n[a].H[c]=b}else n[a]=b,n[a].Z=c},gg=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return b>=48&&b<=57?`_${a}`:a};function hg(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.ba=c;this.Y=d;this.N=e;this.Mb=f;this.va=g;this.Gb=h;this.mc=[]}
var ig=(a,b,c)=>{for(;b!==c;){if(!b.va)throw new W(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.va(a);b=b.N}return a},jg=a=>{if(a===null)return"null";var b=typeof a;return b==="object"||b==="array"||b==="function"?a.toString():""+a};
function kg(a,b){if(b===null){if(this.Ka)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${jg(b)}" as a ${this.name}`);if(!b.l.B)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);return ig(b.l.B,b.l.F.u,this.u)}
function lg(a,b){if(b===null){if(this.Ka)throw new W(`null is not a valid ${this.name}`);if(this.Aa){var c=this.Ra();a!==null&&a.push(this.Y,c);return c}return 0}if(!b||!b.l)throw new W(`Cannot pass "${jg(b)}" as a ${this.name}`);if(!b.l.B)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.za&&b.l.F.za)throw new W(`Cannot convert argument of type ${b.l.R?b.l.R.name:b.l.F.name} to parameter type ${this.name}`);c=ig(b.l.B,b.l.F.u,this.u);if(this.Aa){if(void 0===b.l.K)throw new W("Passing raw pointer to smart pointer is illegal");
switch(this.tc){case 0:if(b.l.R===this)c=b.l.K;else throw new W(`Cannot convert argument of type ${b.l.R?b.l.R.name:b.l.F.name} to parameter type ${this.name}`);break;case 1:c=b.l.K;break;case 2:if(b.l.R===this)c=b.l.K;else{var d=b.clone();c=this.nc(c,mg(()=>d["delete"]()));a!==null&&a.push(this.Y,c)}break;default:throw new W("Unsupported sharing policy");}}return c}
function ng(a,b){if(b===null){if(this.Ka)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${jg(b)}" as a ${this.name}`);if(!b.l.B)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.l.F.za)throw new W(`Cannot convert argument of type ${b.l.F.name} to parameter type ${this.name}`);return ig(b.l.B,b.l.F.u,this.u)}
var og=(a,b,c)=>{if(b===c)return a;if(void 0===c.N)return null;a=og(a,b,c.N);return a===null?null:c.Gb(a)},pg={},qg=(a,b)=>{if(b===void 0)throw new W("ptr should not be undefined");for(;a.N;)b=a.va(b),a=a.N;return pg[b]},rg=(a,b)=>{if(!b.F||!b.B)throw new Rf("makeClassHandle requires ptr and ptrType");if(!!b.R!==!!b.K)throw new Rf("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Zf(Object.create(a,{l:{value:b,writable:!0}}))};
function sg(a,b,c,d,e,f,g,h,k,l,m){this.name=a;this.u=b;this.Ka=c;this.za=d;this.Aa=e;this.lc=f;this.tc=g;this.nb=h;this.Ra=k;this.nc=l;this.Y=m;e||b.N!==void 0?this.G=lg:(this.G=d?kg:ng,this.I=null)}var tg=(a,b,c)=>{if(!n.hasOwnProperty(a))throw new Rf("Replacing nonexistent public symbol");void 0!==n[a].H&&void 0!==c?n[a].H[c]=b:(n[a]=b,n[a].Z=c)},X=(a,b)=>{a=V(a);var c=M.get(b);if(typeof c!="function")throw new W(`unknown function pointer with signature ${a}: ${b}`);return c};
class ug extends Error{}
var vg=a=>{a=dd(a);var b=V(a);L(a);return b},wg=(a,b)=>{function c(f){e[f]||Pf[f]||(Qf[f]?Qf[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new ug(`${a}: `+d.map(vg).join([", "]));},Cb=(a,b,c,d,e,f,g,h,k,l,m,q,t)=>{m=V(m);f=X(e,f);h&&=X(g,h);l&&=X(k,l);t=X(q,t);var p=gg(m);fg(p,function(){wg(`Cannot construct ${m} due to unbound types`,[d])});U([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var v=u.u;var B=v.ba}else B=cg.prototype;u=Ge(m,function(...D){if(Object.getPrototypeOf(this)!==z)throw new W(`Use 'new' to construct ${m}`);
if(void 0===C.ga)throw new W(`${m} has no accessible constructor`);var ka=C.ga[D.length];if(void 0===ka)throw new W(`Tried to invoke ctor of ${m} with invalid number of parameters (${D.length}) - expected (${Object.keys(C.ga).toString()}) parameters instead!`);return ka.apply(this,D)});var z=Object.create(B,{constructor:{value:u}});u.prototype=z;var C=new hg(m,u,z,t,v,f,h,l);if(C.N){var K;(K=C.N).wa??(K.wa=[]);C.N.wa.push(C)}v=new sg(m,C,!0,!1,!1);K=new sg(m+"*",C,!1,!1,!1);B=new sg(m+" const*",C,
!1,!0,!1);dg[a]={pointerType:K,Eb:B};tg(p,u);return[v,K,B]})};Cb.g="vppppppppppppp";function xg(a){for(var b=1;b<a.length;++b)if(a[b]!==null&&a[b].I===void 0)return!0;return!1}
function yg(a,b,c,d,e,f){var g=b.length;if(g<2)throw new W("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=b[1]!==null&&c!==null,k=xg(b);c=!b[0].gb;var l=b[0],m=b[1];d=[a,Sf,d,e,Mf,l.A.bind(l),m?.G.bind(m)];for(e=2;e<g;++e)l=b[e],d.push(l.G.bind(l));if(!k)for(e=h?1:2;e<b.length;++e)b[e].I!==null&&d.push(b[e].I);k=xg(b);e=b.length-2;m=[];l=["fn"];h&&l.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),l.push(`arg${g}Wired`);m=m.join(",");l=l.join(",");m=`return function (${m}) {\n`;
k&&(m+="var destructors = [];\n");var q=k?"destructors":"null",t="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(m+=`var thisWired = toClassParamWire(${q}, this);\n`);for(g=0;g<e;++g){var p=`toArg${g}Wire`;m+=`var arg${g}Wired = ${p}(${q}, arg${g});\n`;t.push(p)}m+=(c||f?"var rv = ":"")+`invoker(${l});\n`;if(k)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=g===1?"thisWired":"arg"+(g-2)+"Wired",b[g].I!==null&&(m+=`${f}_dtor(${f});\n`,
t.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(t,m+"}\n"))(...d);return Ge(a,b)}
var zg=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(G[b+d*4>>2]);return c},Bg=a=>{a=a.trim();var b=a.indexOf("(");return b===-1?a:a.slice(0,b)},Db=(a,b,c,d,e,f,g,h)=>{var k=zg(c,d);b=V(b);b=Bg(b);f=X(e,f);U([],[a],l=>{function m(){wg(`Cannot call ${q} due to unbound types`,k)}l=l[0];var q=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var t=l.u.constructor;void 0===t[b]?(m.Z=c-1,t[b]=m):(eg(t,b,q),t[b].H[c-1]=m);U([],k,p=>{p=yg(q,[p[0],null].concat(p.slice(1)),null,f,g,h);void 0===t[b].H?
(p.Z=c-1,t[b]=p):t[b].H[c-1]=p;if(l.u.wa)for(let u of l.u.wa)u.constructor.hasOwnProperty(b)||(u.constructor[b]=p);return[]});return[]})};Db.g="vppippppii";
var Eb=(a,b,c,d,e,f)=>{var g=zg(b,c);e=X(d,e);U([],[a],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.u.ga&&(h.u.ga=[]);if(void 0!==h.u.ga[b-1])throw new W(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.u.ga[b-1]=()=>{wg(`Cannot construct ${h.name} due to unbound types`,g)};U([],g,l=>{l.splice(1,0,null);h.u.ga[b-1]=yg(k,l,null,e,f);return[]});
return[]})};Eb.g="vpipppp";var Fb=(a,b,c,d,e,f,g,h,k)=>{var l=zg(c,d);b=V(b);b=Bg(b);f=X(e,f);U([],[a],m=>{function q(){wg(`Cannot call ${t} due to unbound types`,l)}m=m[0];var t=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&m.u.mc.push(b);var p=m.u.ba,u=p[b];void 0===u||void 0===u.H&&u.className!==m.name&&u.Z===c-2?(q.Z=c-2,q.className=m.name,p[b]=q):(eg(p,b,t),p[b].H[c-2]=q);U([],l,v=>{v=yg(t,v,m,f,g,k);void 0===p[b].H?(v.Z=c-2,p[b]=v):p[b].H[c-2]=v;return[]});return[]})};
Fb.g="vppippppiii";
var Cg=(a,b,c)=>{if(!(a instanceof Object))throw new W(`${c} with invalid "this": ${a}`);if(!(a instanceof b.u.constructor))throw new W(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.l.B)throw new W(`cannot call emscripten binding method ${c} on deleted object`);return ig(a.l.B,a.l.F.u,b.u)},Gb=(a,b,c,d,e,f,g,h,k,l)=>{b=V(b);e=X(d,e);U([],[a],m=>{m=m[0];var q=`${m.name}.${b}`,t={get(){wg(`Cannot access ${q} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};t.set=k?
()=>wg(`Cannot access ${q} due to unbound types`,[c,g]):()=>{throw new W(q+" is a read-only property");};Object.defineProperty(m.u.ba,b,t);U([],k?[c,g]:[c],p=>{var u=p[0],v={get(){var z=Cg(this,m,q+" getter");return u.A(e(f,z))},enumerable:!0};if(k){k=X(h,k);var B=p[1];v.set=function(z){var C=Cg(this,m,q+" setter"),K=[];k(l,C,B.G(K,z));Mf(K)}}Object.defineProperty(m.u.ba,b,v);return[]});return[]})};Gb.g="vpppppppppp";
var Dg=[],Eg=[0,1,,1,null,1,!0,1,!1,1],Fg=[],hc=a=>{if(a>9&&0===--Eg[a+1]){var b=Eg[a];Eg[a]=void 0;var c=Fg[a];c&&(Fg[a]=void 0,c(b));Dg.push(a)}};hc.g="vp";var Z=a=>{if(!a)throw new W(`Cannot use deleted val. handle = ${a}`);return Eg[a]},mg=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:let b=Dg.pop()||Eg.length;Eg[b]=a;Eg[b+1]=1;return b}},Gg={name:"emscripten::val",A:a=>{var b=Z(a);hc(a);return b},G:(a,b)=>mg(b),L:Nf,I:null},Hb=a=>T(a,Gg);
Hb.g="vp";
var Hg=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.A(x[d])}:function(d){return this.A(A[d])};case 2:return c?function(d){return this.A(y[d>>1])}:function(d){return this.A(E[d>>1])};case 4:return c?function(d){return this.A(F[d>>2])}:function(d){return this.A(G[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ib=(a,b,c,d,e)=>{b=V(b);e=e===0?"object":e===1?"number":"string";switch(e){case "object":function g(){}g.values={};T(a,{name:b,constructor:g,valueType:e,
A:function(h){return this.constructor.values[h]},G:(h,k)=>k.value,L:Hg(b,c,d),I:null});fg(b,g);break;case "number":var f={};T(a,{name:b,La:f,valueType:e,A:h=>h,G:(h,k)=>k,L:Hg(b,c,d),I:null});fg(b,f);delete n[b].Z;break;case "string":f={},T(a,{name:b,ub:{},ob:{},La:f,valueType:e,A:function(h){return this.ob[h]},G:function(h,k){return this.ub[k]},L:Hg(b,c,d),I:null}),fg(b,f),delete n[b].Z}};Ib.g="vpppii";
var Ig=(a,b)=>{var c=Pf[a];if(void 0===c)throw a=`${b} has unknown type ${vg(a)}`,new W(a);return c},Jb=(a,b,c)=>{var d=Ig(a,"enum");b=V(b);switch(d.valueType){case "object":a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ge(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d;break;case "number":d.La[b]=c;break;case "string":d.ub[b]=c,d.ob[c]=b,d.La[b]=b}};Jb.g="vppi";
var Jg=(a,b)=>{switch(b){case 4:return function(c){return this.A(La[c>>2])};case 8:return function(c){return this.A(Ma[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Kb=(a,b,c)=>{b=V(b);T(a,{name:b,A:d=>d,G:(d,e)=>e,L:Jg(b,c),I:null})};Kb.g="vppp";var Lb=(a,b,c,d,e,f,g)=>{var h=zg(b,c);a=V(a);a=Bg(a);e=X(d,e);fg(a,function(){wg(`Cannot call ${a} due to unbound types`,h)},b-1);U([],h,k=>{tg(a,yg(a,[k[0],null].concat(k.slice(1)),null,e,f,g),b-1);return[]})};Lb.g="vpippppii";
var Mb=(a,b,c,d,e)=>{b=V(b);var f=h=>h;if(d===0){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}T(a,{name:b,A:f,G:(h,k)=>k,L:Uf(b,c,d!==0),I:null})};Mb.g="vpppii";var Kg=(a,b,c)=>{var d=(e,f)=>{var g=0;return{next(){if(g>=e)return{done:!0};var h=g;g++;return{value:f(h),done:!1}},[Symbol.iterator](){return this}}};a[Symbol.iterator]||(a[Symbol.iterator]=function(){var e=this[b]();return d(e,f=>this[c](f))})},Nb=(a,b,c,d)=>{c=V(c);d=V(d);U([],[a,b],e=>{Kg(e[0].u.ba,c,d);return[]})};Nb.g="vpppp";
var Ob=(a,b,c)=>{function d(f){return new e(x.buffer,G[f+4>>2],G[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=V(c);T(a,{name:c,A:d,L:d},{Ub:!0})};Ob.g="vpip";var Lg=Object.assign({optional:!0},Gg),Pb=a=>{T(a,Lg)};Pb.g="vpp";
var Qb=(a,b)=>{b=V(b);T(a,{name:b,A(c){var d=P(c+4,G[c>>2],!0);L(c);return d},G(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e=typeof d=="string";if(!(e||ArrayBuffer.isView(d)&&d.BYTES_PER_ELEMENT==1))throw new W("Cannot pass non-string to std::string");var f=e?Ue(d):d.length;var g=ad(4+f+1),h=g+4;G[g>>2]=f;e?Q(d,A,h,f+1):A.set(d,h);c!==null&&c.push(L,g);return g},L:Nf,I(c){L(c)}})};Qb.g="vpp";
var Mg=new TextDecoder("utf-16le"),Ng=(a,b,c)=>{a>>=1;return Mg.decode(E.slice(a,qe(E,a,b/2,c)))},Og=(a,b,c)=>{c??=2147483647;if(c<2)return 0;c-=2;var d=b;c=c<a.length*2?c/2:a.length;for(var e=0;e<c;++e)y[b>>1]=a.charCodeAt(e),b+=2;y[b>>1]=0;return b-d},Pg=a=>a.length*2,Qg=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=G[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Rg=(a,b,c)=>{c??=2147483647;if(c<4)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);
f>65535&&e++;F[b>>2]=f;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d},Sg=a=>{for(var b=0,c=0;c<a.length;++c)a.codePointAt(c)>65535&&c++,b+=4;return b},Rb=(a,b,c)=>{c=V(c);if(b===2){var d=Ng;var e=Og;var f=Pg}else d=Qg,e=Rg,f=Sg;T(a,{name:c,A:g=>{var h=d(g+4,G[g>>2]*b,!0);L(g);return h},G:(g,h)=>{if(typeof h!="string")throw new W(`Cannot pass non-string to C++ string type ${c}`);var k=f(h),l=ad(4+k+b);G[l>>2]=k/b;e(h,l+4,k+b);g!==null&&g.push(L,l);return l},L:Nf,I(g){L(g)}})};Rb.g="vppp";
var Sb=(a,b,c,d,e,f)=>{Lf[a]={name:V(b),Ra:X(c,d),Y:X(e,f),bb:[]}};Sb.g="vpppppp";var Tb=(a,b,c,d,e,f,g,h,k,l)=>{Lf[a].bb.push({Kb:V(b),Qb:c,na:X(d,e),Pb:f,qc:g,oc:X(h,k),rc:l})};Tb.g="vpppppppppp";var Ub=(a,b)=>{b=V(b);T(a,{gb:!0,name:b,A:()=>{},G:()=>{}})};Ub.g="vpp";var Vb=(a,b,c,d)=>{function e(h){var k=P(a+36);Jf(`'Could not load dynamic lib: ${k}\n${h}`);--N;be(()=>M.get(c)(a,d))}function f(){--N;be(()=>M.get(b)(a,d))}N+=1;var g=Kf(a,{J:!0});g?g.then(f,e):e()};Vb.g="vpppp";
function Tg(a){var b=Ug,c=b.ia.pop()??b.fa.length;b.fa[c]=a;return c}function Vg(a){var b=Ug;b.fa[a]=void 0;b.ia.push(a)}class Wg{fa=[void 0];ia=[];get(a){return this.fa[a]}has(a){return this.fa[a]!==void 0}}
var Ug=new Wg,Xg=()=>{var a={};a.promise=new Promise((b,c)=>{a.reject=c;a.resolve=b});a.id=Tg(a);return a},Yg=async()=>{var a=ce,b=[],c=Xg();b.push(c.promise);hd(c.id);for(let d of Object.keys(Id)){let e=Number(d);e===a||Jd.has(e)||(c=Xg(),kd(e,c.id),Kd[e]=c,b.push(c.promise))}await Promise.all(b);Kd={}};function Wb(){if(r)return O(17,2);if(ce)return Yg();for(let a of Object.keys(Id)){let b=Number(a);Jd.has(b)||ld(b)}}Wb.g="v";
function Xb(){var a=ad((ma.length+1)*4),b=a;ma.forEach(c=>{var d=G,e=b>>2,f=Ue(c)+1,g=ad(f);g&&Q(c,A,g,f);d[e]=g;b+=4});G[b>>2]=0;return a}Xb.g="p";var Yb=a=>{var b=!aa;try{Atomics.wait(F,0,0,0),b=!0}catch(c){}Ca(a,!ba,1,b,262144,!1);Da()};Yb.g="vp";var Ea=a=>{Xd||(Atomics.waitAsync(F,a>>2,a).value.then(Ha),Atomics.store(F,a+112>>2,1))};Ea.g="vp";var Ha=()=>{var a=$c();a&&be(()=>{Ea(a);sd()})},Zb=(a,b)=>{a==b?setTimeout(Ha):r?postMessage({rb:a,V:4}):(a=Id[a])&&a.postMessage({V:4})};Zb.g="vpp";
var Zg=[],$b=(a,b,c,d,e,f,g)=>{Zg.length=0;var h=e>>3;for(d=e+d>>3;h<d;){var k;H[h++]?k=H[h++]:k=Ma[h++];Zg.push(k)}a=b?Ie[b]:$g[a];ce=c;c=a(...Zg);ce=0;if(f)c.then(l=>od(f,g,l));else return c};$b.g="dippippp";var ac=()=>{de=!1;N=0};ac.g="v";var bc=a=>{r?postMessage({V:6,Ua:a}):Md(a)};bc.g="vp";var cc=a=>{r?postMessage({V:7,Ua:a}):Pd(a)};cc.g="vp";var dc=()=>{};dc.g="vp";var ec=(a,b)=>{a=Z(a);b=Z(b);a.set(b)};ec.g="vpp";
var ah=[],bh=a=>{var b=ah.length;ah.push(a);return b},ch=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Ig(G[b+d*4>>2],`parameter ${d}`);return c},dh=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(G[b>>2]=mg(d));return a},eh={},fh=a=>{var b=eh[a];return b===void 0?V(a):b},fc=(a,b,c)=>{var d;[b,...d]=ch(a,b);var e=b.G.bind(b),f=d.map(k=>k.L.bind(k));a--;var g={toValue:Z};a=f.map((k,l)=>{var m=`argFromPtr${l}`;g[m]=k;return`${m}(args${l?"+"+l*8:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";
break;case 3:h="";break;case 1:g.getStringOrSymbol=fh,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;b.gb||(g.toReturnWire=e,g.emval_returnValue=dh,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n${h}\n}`;c=(new Function(Object.keys(g),h))(...Object.values(g));b=`methodCaller<(${d.map(k=>k.name)}) => ${b.name}>`;return bh(Ge(b,c))};fc.g="pipi";var ic=a=>{if(!a)return mg(globalThis);a=fh(a);return mg(globalThis[a])};
ic.g="pp";var jc=a=>{a=fh(a);return mg(n[a])};jc.g="pp";var kc=(a,b)=>{a=Z(a);b=Z(b);return mg(a[b])};kc.g="ppp";var lc=a=>{a>9&&(Eg[a+1]+=1)};lc.g="vp";var mc=(a,b)=>{a=Z(a);b=Z(b);return a instanceof b};mc.g="ipp";var nc=(a,b,c,d,e)=>ah[a](b,c,d,e);nc.g="dppppp";var oc=a=>{a=Z(a);return typeof a=="number"};oc.g="ip";var pc=a=>{a=Z(a);return typeof a=="string"};pc.g="ip";var qc=a=>mg(fh(a));qc.g="pp";var rc=a=>{var b=Z(a);Mf(b);hc(a)};rc.g="vp";var sc=(a,b,c)=>{a=Z(a);b=Z(b);c=Z(c);a[b]=c};
sc.g="vppp";var tc=a=>{a=Z(a);return mg(typeof a)};tc.g="pp";function uc(a,b){a=a<-9007199254740992||a>9007199254740992?NaN:Number(a);a=new Date(a*1E3);F[b>>2]=a.getUTCSeconds();F[b+4>>2]=a.getUTCMinutes();F[b+8>>2]=a.getUTCHours();F[b+12>>2]=a.getUTCDate();F[b+16>>2]=a.getUTCMonth();F[b+20>>2]=a.getUTCFullYear()-1900;F[b+24>>2]=a.getUTCDay();F[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0}uc.g="vjp";
var gh=[0,31,60,91,121,152,182,213,244,274,305,335],hh=[0,31,59,90,120,151,181,212,243,273,304,334];
function vc(a,b){a=a<-9007199254740992||a>9007199254740992?NaN:Number(a);a=new Date(a*1E3);F[b>>2]=a.getSeconds();F[b+4>>2]=a.getMinutes();F[b+8>>2]=a.getHours();F[b+12>>2]=a.getDate();F[b+16>>2]=a.getMonth();F[b+20>>2]=a.getFullYear()-1900;F[b+24>>2]=a.getDay();var c=a.getFullYear();F[b+28>>2]=(c%4!==0||c%100===0&&c%400!==0?hh:gh)[a.getMonth()]+a.getDate()-1|0;F[b+36>>2]=-(a.getTimezoneOffset()*60);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
F[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0}vc.g="vjp";function wc(a,b,c,d,e,f,g){if(r)return O(18,1,a,b,c,d,e,f,g);e=e<-9007199254740992||e>9007199254740992?NaN:Number(e);try{var h=S(d),k=FS.ka(h,a,e,b,c),l=k.B;F[f>>2]=k.fa;G[g>>2]=l;return 0}catch(m){if(typeof FS=="undefined"||m.name!=="ErrnoError")throw m;return-m.C}}wc.g="ipiiijpp";
function xc(a,b,c,d,e,f){if(r)return O(19,1,a,b,c,d,e,f);f=f<-9007199254740992||f>9007199254740992?NaN:Number(f);try{var g=S(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.h(43);d&2||FS.ma(g,A.slice(a,a+b),c,b,d)}}catch(h){if(typeof FS=="undefined"||h.name!=="ErrnoError")throw h;return-h.C}}xc.g="ippiiij";
var yc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();G[a>>2]=Math.max(f,e)*60;F[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${g>=0?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Q(a,A,c,17),Q(b,A,d,17)):(Q(a,A,d,17),Q(b,A,c,17))};yc.g="vpppp";var Fc=()=>performance.timeOrigin+performance.now();Fc.g="d";var Bc=()=>Date.now();Bc.g="d";var ih=1;
function zc(a,b,c){if(!(a>=0&&a<=3))return 28;if(a===0)a=Date.now();else if(ih)a=performance.timeOrigin+performance.now();else return 52;H[c>>3]=BigInt(Math.round(a*1E3*1E3));return 0}zc.g="iijp";var Ac=()=>{};Ac.g="v";var Cc=a=>w(P(a));Cc.g="vp";var Dc=()=>{N+=1;throw"unwind";};Dc.g="v";var Ec=()=>A.length;Ec.g="p";var Gc=()=>navigator.hardwareConcurrency;Gc.g="i";var Hc=a=>{Vg(a)};Hc.g="vp";
var Ic=(a,b,c)=>{a=Ug.get(a);switch(b){case 0:a.resolve(c);break;case 1:a.resolve(Ug.get(c).promise);break;case 2:a.resolve(Ug.get(c).promise);Vg(c);break;case 3:a.reject(c)}};Ic.g="vpip";var Jc=()=>!1;Jc.g="ip";
var jh={},lh=()=>{if(!kh){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:da},b;for(b in jh)jh[b]===void 0?delete a[b]:a[b]=jh[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);kh=c}return kh},kh;function Kc(a,b){if(r)return O(20,1,a,b);var c=0,d=0,e;for(e of lh()){var f=b+c;G[a+d>>2]=f;c+=Q(e,A,f,Infinity)+1;d+=4}return 0}Kc.g="ipp";
function Lc(a,b){if(r)return O(21,1,a,b);var c=lh();G[a>>2]=c.length;a=0;for(var d of c)a+=Ue(d)+1;G[b>>2]=a;return 0}Lc.g="ipp";function Nc(a){if(r)return O(22,1,a);try{var b=S(a);FS.close(b);return 0}catch(c){if(typeof FS=="undefined"||c.name!=="ErrnoError")throw c;return c.C}}Nc.g="ii";
function Oc(a,b){if(r)return O(23,1,a,b);try{var c=S(a),d=c.D?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;x[b]=d;y[b+2>>1]=0;H[b+8>>3]=BigInt(0);H[b+16>>3]=BigInt(0);return 0}catch(e){if(typeof FS=="undefined"||e.name!=="ErrnoError")throw e;return e.C}}Oc.g="iip";
function Pc(a,b,c,d){if(r)return O(24,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var h=G[a>>2],k=G[a+4>>2];a+=8;var l=FS.read(e,x,h,k,f);if(l<0){var m=-1;break a}b+=l;if(l<k)break;typeof f!="undefined"&&(f+=l)}m=b}G[d>>2]=m;return 0}catch(q){if(typeof FS=="undefined"||q.name!=="ErrnoError")throw q;return q.C}}Pc.g="iippp";
function Qc(a,b,c,d){if(r)return O(25,1,a,b,c,d);b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=S(a);FS.llseek(e,b,c);H[d>>3]=BigInt(e.position);e.Ga&&b===0&&c===0&&(e.Ga=null);return 0}catch(f){if(typeof FS=="undefined"||f.name!=="ErrnoError")throw f;return f.C}}Qc.g="iijip";
function Rc(a,b,c,d){if(r)return O(26,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var h=G[a>>2],k=G[a+4>>2];a+=8;var l=FS.write(e,x,h,k,f);if(l<0){var m=-1;break a}b+=l;if(l<k)break;typeof f!="undefined"&&(f+=l)}m=b}G[d>>2]=m;return 0}catch(q){if(typeof FS=="undefined"||q.name!=="ErrnoError")throw q;return q.C}}Rc.g="iippp";function Tc(...a){return J.heif_error_success(...a)}Tc.Ca=!0;var Vc=(a,b)=>Xe(A.subarray(a,a+b));Vc.g="ipp";r||Zd();
(()=>{var a={mb:Promise.resolve(),canHandle:b=>!n.noWasmDecoding&&b.endsWith(".so"),handle:async(b,c)=>a.mb=a.mb.then(async()=>{try{var d=await Me(b,{J:!0,qa:!0},c,{})}catch(e){throw Error(`failed to instantiate wasm: ${c}: ${e}`);}he[c]=d;return b})};ge.push(a)})();FS.createPreloadedFile=(a,b,c,d,e,f,g,h,k,l)=>{nf(a,b,c,d,e,h,k,l).then(f).catch(g)};FS.Sc=nf;FS.da=Array(4096);FS.mount(R,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));cf(FS.makedev(5,0),ef);cf(FS.makedev(6,0),ff);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{b===0&&(Xe(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.o={llseek:R.o.llseek};b.m={ja(c,d){c=+d;var e=S(c);c={parent:null,mount:{jb:"fake"},m:{readlink:()=>e.path},id:c+1};return c.parent=c},ta(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();FS.Lb={MEMFS:R};
(()=>{var a=cg.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof cg&&c instanceof cg))return!1;var d=this.l.F.u,e=this.l.B;c.l=c.l;var f=c.l.F.u;for(c=c.l.B;d.N;)e=d.va(e),d=d.N;for(;f.N;)c=f.va(c),f=f.N;return d===f&&e===c},clone:function(){this.l.B||Vf(this);if(this.l.ra)return this.l.count.value+=1,this;var c=Zf,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.l;c=c(e.call(d,f,{l:{value:{count:g.count,ha:g.ha,ra:g.ra,B:g.B,F:g.F,K:g.K,R:g.R}}}));c.l.count.value+=1;c.l.ha=
!1;return c},["delete"](){this.l.B||Vf(this);if(this.l.ha&&!this.l.ra)throw new W("Object already scheduled for deletion");Yf(this);var c=this.l;--c.count.value;0===c.count.value&&(c.K?c.R.Y(c.K):c.F.u.Y(c.B));this.l.ra||(this.l.K=void 0,this.l.B=void 0)},isDeleted:function(){return!this.l.B},deleteLater:function(){this.l.B||Vf(this);if(this.l.ha&&!this.l.ra)throw new W("Object already scheduled for deletion");$f.push(this);$f.length===1&&bg&&bg(ag);this.l.ha=!0;return this}});var b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(sg.prototype,{Ob(a){this.nb&&(a=this.nb(a));return a},Ya(a){this.Y?.(a)},L:Nf,A:function(a){function b(){return this.Aa?rg(this.u.ba,{F:this.lc,B:c,R:this,K:a}):rg(this.u.ba,{F:this,B:a})}var c=this.Ob(a);if(!c)return this.Ya(a),null;var d=qg(this.u,c);if(void 0!==d){if(0===d.l.count.value)return d.l.B=c,d.l.K=a,d.clone();d=d.clone();this.Ya(a);return d}d=this.u.Mb(c);d=dg[d];if(!d)return b.call(this);d=this.za?d.Eb:d.pointerType;var e=og(c,this.u,d.u);return e===null?b.call(this):this.Aa?
rg(d.u.ba,{F:d,B:e,R:this,K:a}):rg(d.u.ba,{F:d,B:e})}});Nd.push(()=>{jh.VIPS_DISC_THRESHOLD=1073741824;jh.VIPS_MAX_THREADS=navigator.hardwareConcurrency>6?navigator.hardwareConcurrency:6;jh.VIPS_CONCURRENCY=1});
Sa.push(()=>{var a=Object.getOwnPropertyDescriptor(n.SourceCustom.prototype,"onRead");Object.defineProperty(n.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>mg(c(d)))}});var b=Object.getOwnPropertyDescriptor(n.TargetCustom.prototype,"onWrite");Object.defineProperty(n.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(Z(d)))}})});Object.assign(cg.prototype,{preventAutoDelete:function(){var a=$f.indexOf(this);a>-1&&$f.splice(a,1);this.l.ha=!1;return this}});
if(!r){if(n.wasmMemory)xa=n.wasmMemory;else{var mh=n.INITIAL_MEMORY||1073741824;xa=new WebAssembly.Memory({initial:mh/65536,maximum:mh/65536,shared:!0})}ya()}n.preloadPlugins&&(ge=n.preloadPlugins);n.noExitRuntime&&(de=n.noExitRuntime);n.print&&(la=n.print);n.printErr&&(w=n.printErr);n.dynamicLibraries&&(ma=n.dynamicLibraries);n.wasmBinary&&(na=n.wasmBinary);n.arguments&&(ca=n.arguments);n.thisProgram&&(da=n.thisProgram);
if(n.preInit)for(typeof n.preInit=="function"&&(n.preInit=[n.preInit]);n.preInit.length>0;)n.preInit.shift()();n.ENV=jh;n.addRunDependency=Td;n.removeRunDependency=Sd;n.addFunction=De;n.FS_preloadFile=nf;n.FS_unlink=(...a)=>FS.unlink(...a);n.FS_createPath=(...a)=>FS.createPath(...a);n.FS_createDevice=(...a)=>FS.createDevice(...a);n.FS=FS;n.FS_createDataFile=(...a)=>FS.createDataFile(...a);n.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);n.setAutoDeleteLater=a=>{Wf=a};n.deletionQueue=$f;
n.setDelayFunction=a=>{bg=a;$f.length&&bg&&bg(ag)};var $g=[Uc,ee,Df,db,eb,fb,gb,hb,ib,jb,kb,lb,mb,nb,ob,pb,qb,Wb,wc,xc,Kc,Lc,Nc,Oc,Pc,Qc,Rc],Ie={};function nh(a){for(var b=E[a+6>>1];b===13&&!(G[a>>2]>16);){var c=G[a+8>>2],d=G[c>>2];if(d===0){b=0;break}else if(G[(c>>2)+1]===0)a=d,b=E[d+6>>1];else break}return[a,b]}
function Sc(a,b,c,d){var e=G[(a>>2)+1],f=G[(a>>2)+6],g=G[(a>>2)+2],h=G[(a>>2)+5];a=nh(G[(a>>2)+3])[1];var k=xd(),l=k,m=[],q=!1;if(a===15)throw Error("complex ret marshalling nyi");if(a<0||a>15)throw Error("Unexpected rtype "+a);if(a===4||a===13)m.push(c),q=!0;for(var t=0;t<f;t++){var p=G[(d>>2)+t],u=nh(G[(g>>2)+t]),v=u[0];u=u[1];switch(u){case 1:case 10:case 9:m.push(G[p>>2]);break;case 2:m.push(La[p>>2]);break;case 3:m.push(Ma[p>>3]);break;case 5:m.push(A[p]);break;case 6:m.push(x[p]);break;case 7:m.push(E[p>>
1]);break;case 8:m.push(y[p>>1]);break;case 11:case 12:m.push(Na[p>>3]);break;case 4:m.push(Na[p>>3]);m.push(Na[(p>>3)+1]);break;case 13:u=G[v>>2];v=E[v+4>>1];l-=u;l&=~(v-1);x.subarray(l,l+u).set(x.subarray(p,p+u));m.push(l);break;case 14:m.push(G[p>>2]);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+u);}}if(h&1){h=[];for(t=e-1;t>=f;t--)switch(p=G[(d>>2)+t],u=nh(G[(g>>2)+t]),v=u[0],u=u[1],u){case 5:case 6:--l;l&=-1;A[l]=A[p];break;case 7:case 8:l-=2;l&=
-2;E[l>>1]=E[p>>1];break;case 1:case 9:case 10:case 2:l-=4;l&=-4;G[l>>2]=G[p>>2];break;case 3:case 11:case 12:l-=8;l&=-8;G[l>>2]=G[p>>2];G[(l>>2)+1]=G[(p>>2)+1];break;case 4:l-=16;l&=-8;G[l>>2]=G[p>>2];G[(l>>2)+1]=G[(p>>2)+1];G[(l>>2)+2]=G[(p>>2)+2];G[(l>>2)+3]=G[(p>>2)+3];break;case 13:l-=4;l&=-4;h.push([l,p,G[v>>2],E[v+4>>1]]);break;case 14:l-=4;l&=-4;G[l>>2]=G[p>>2];break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+u);}m.push(l);for(t=0;t<h.length;t++)e=
h[t],d=e[0],p=e[1],u=e[2],v=e[3],l-=u,l&=~(v-1),x.subarray(l,l+u).set(x.subarray(p,p+u)),G[d>>2]=l}vd(l);wd(0);b=M.get(b).apply(null,m);vd(k);if(!q)switch(a){case 0:break;case 1:case 9:case 10:G[c>>2]=b;break;case 2:La[c>>2]=b;break;case 3:Ma[c>>3]=b;break;case 5:case 6:A[c+0]=b;break;case 7:case 8:E[c>>1]=b;break;case 11:case 12:Na[c>>3]=b;break;case 14:G[c>>2]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}Sc.g="viiii";
var $c,ad,L,bd,cd,dd,Fa,ed,fd,gd,hd,jd,kd,ld,md,Ca,nd,Ia,od,pd,qd,rd,sd,td,Ta,ud,vd,wd,xd,yd,zd,Ad,Bd,M,J;function oh(a=[]){var b=He("main").Ta;if(b){a.unshift(da);var c=a.length,d=wd((c+1)*4),e=d,f;for(f of a)G[e>>2]=Ve(f),e+=4;G[e>>2]=0;try{var g=b(c,d);Mc(g,!0)}catch(h){Gd(h)}}}
function Aa(a=ca){function b(){n.calledRun=!0;if(!pa&&(Pa(),ra?.(n),n.onRuntimeInitialized?.(),n.noInitialRun||oh(a),!r)){if(n.postRun)for(typeof n.postRun=="function"&&(n.postRun=[n.postRun]);n.postRun.length;){var c=n.postRun.shift();oe.push(c)}Qa(oe)}}if(Qd>0)Rd=Aa;else if(r)ra?.(n),Pa();else{if(n.preRun)for(typeof n.preRun=="function"&&(n.preRun=[n.preRun]);n.preRun.length;)Od();Qa(Nd);Qd>0?Rd=Aa:n.setStatus?(n.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>n.setStatus(""),1);b()},1)):
b()}}var Ra;r||(Ra=await (za()),Aa());Ja?moduleRtn=n:moduleRtn=new Promise((a,b)=>{ra=a;sa=b});
;return moduleRtn}export default Vips;var isPthread=globalThis.name=="em-pthread";isPthread&&Vips();
